---
title: "Clase 1 Modelacion de cultivos"
author: "Sergio A Hernández"
date: "27/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Escalas de medida

###Nominal
```{r}
gentp=gl(5,5,25, labels=paste0('G', 1:5))
tabla=table(gentp)# Tabulación
prop.table(tabla)

```
### Ordinal

Escala nominal asociado a un orden. Ejemplo, escala de una enfermedad.

```{r}
escala=sample(1:5,size=50,replace=T);escala
#5= Negativo
#4= Trazas de la enfermedad
#3= Grado 3
#2= Grado 2
#1= Grado1
tabla=table(escala); tabla
prop=prop.table(tabla);prop



```

### Intervalo


```{r}
set.seed(123)
tempc=rnorm(120,14.5,1.3)
tempk=tempc+273
plot(tempc,tempk, xlim=c(0,18), ylim=c(0,300))
maxk=max(tempk);maxk
mink=min(tempk);mink
rgk= maxk-mink;rgk #rango de la temperatura# Es falso debido a que no se ordenaron los datos


#cambio relativo
crl=(maxk-mink)/(mink); crl
hist(tempk)
abline(v=c(maxk,mink))
#donde esta el maximo
posmax=which.max(tempk);posmax
posmin=which.min(tempk);posmin

plot(tempk,type='l')
abline(v=c(posmin,posmax), col=c('blue','red'))
rgk




```
```{r}
clorofila_t0=350
clorofila_tf=400
# Cambio absoluto
absclf=clorofila_tf-clorofila_t0; absclf
# CAmbio relativo
rltclf= 100*(absclf)/(clorofila_t0); rltclf
# Warning: el cero de la escala es falso, el cero no es real. es un cero relativo, es impuetso a la fuerza y no representa un fenomeno real


```
¿El cero de la escala existe o no existe?
Ejemplo de la temperatura

```{r}

```